SignalRMapDemo/Controllers/ChatController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SignalRMapDemo.Controllers
{
    public class ChatController : Controller
    {
        // GET: Chat
        public ActionResult Index()
        {
            return View();
        }
    }
}

SignalRMapDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SignalRMapDemo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

SignalRMapDemo/Controllers/MapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SignalRMapDemo.Controllers
{
    public class MapController : Controller
    {
        // GET: Map
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Leaflet()
        {
            return View();
        }
        [HttpGet]
        public ActionResult Mobile()
        {
            return View();
        }

        [HttpGet]
        public ActionResult NewMap()
        {
            ViewBag.userName = null;
            return View();
        }

        [HttpPost]
        public ActionResult NewMap(string userName)
        {
            ViewBag.userName = userName;
            return View();
        }
        [HttpGet]
        public ActionResult PureLeaflet()
        {
            ViewBag.userName = null;
            return View();
        }

        [HttpPost]
        public ActionResult PureLeaflet(string userName)
        {
            ViewBag.userName = userName;
            return View();
        }


        [HttpPost]
        public JsonResult Create(string dataz)
        {
            //JavaScriptSerializer js = new JavaScriptSerializer();
            //Person[] persons = js.Deserialize<Person[]>(json);
            JavaScriptSerializer sr = new JavaScriptSerializer();
            ServiceReference1.Locations objCoord = sr.Deserialize<ServiceReference1.Locations>(dataz);

            ServiceReference1.Service1Client obj = new ServiceReference1.Service1Client("Service1");
            //obj.SaveData();
             string msg =  obj.SaveData(objCoord);
             return Json("Success ;) " + msg);
        }
    }

    //public class Locations
    //{
        
    //    public Int32 locID { get; set; }
    //    public String locName { get; set; }
    //    public String userName { get; set; }
    //    public String latitude { get; set; }
    //    public String longitude { get; set; }
    //    public DateTime date { get; set; }
    //}
}

SignalRMapDemo/Views/Chat/Index.cshtml
@{
    ViewBag.Title = "Chat";
}
<h2>Chat</h2>
<div class="container">
    <input type="text" id="message" />
    <input type="button" id="sendmessage" value="Send" />
    <input type="hidden" id="displayname" />
    <ul id="discussion"></ul>
</div>
@section scripts {
    <!--Script references. -->
    <!--The jQuery library is required and is referenced by default in _Layout.cshtml. -->
    <!--Reference the SignalR library. -->
    <script src="~/Scripts/jquery.signalR-2.2.0.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>
    <!--SignalR script to update the chat page and send messages.-->
    <script>
        jQuery(function () {
            // Reference the auto-generated proxy for the hub.
            var chat = jQuery.connection.getRoutes;
            // Create a function that the hub can call back to display messages.
            chat.client.addNewMessageToPage = function (name, message) {
                // Add the message to the page.
                jQuery('#discussion').append('<li><strong>' + htmlEncode(name)
                    + '</strong>: ' + htmlEncode(message) + '</li>');
            };
            // Get the user name and store it to prepend to messages.
            jQuery('#displayname').val(prompt('Enter your name:', ''));
            // Set initial focus to message input box.
            jQuery('#message').focus();
            // Start the connection.
            jQuery.connection.hub.start().done(function () {
                jQuery('#sendmessage').click(function () {
                    // Call the Send method on the hub.
                    chat.server.send(jQuery('#displayname').val(), jQuery('#message').val());
                    // Clear text box and reset focus for next comment.
                    jQuery('#message').val('').focus();
                });
            });
        });
        // This optional function html-encodes messages for display in the page.
        function htmlEncode(value) {
            var encodedValue = jQuery('<div />').text(value).html();
            return encodedValue;
        }
    </script>
}

SignalRMapDemo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

SignalRMapDemo/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

SignalRMapDemo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

SignalRMapDemo/Views/Map/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

SignalRMapDemo/Views/Map/Index.cshtml
@{
    //ViewBag.Title = "Index";
}

<style>
    #map{height:300px;}
</style>

<input type="hidden" id="displayname" />
<div id="map"></div>
<div id="errorcode"></div>
<div id="errormsg"></div>


@section scripts {

<script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCADUnyCKT8Y-MOOvJ5KvYKYVnnJ-wHUyQ">
</script>
@*<script src="~/Scripts/jquery-1.10.2.min.js"></script>*@

<script src="~/Scripts/jquery.signalR-2.2.0.js"></script>
<script src="~/signalr/hubs"></script>
<script>
    

    jQuery(document).ready(function () {
        var currentLoc; // = new google.maps.LatLng(41.850, -87.650);
        var map;
        var mymarker;
        var options = {
            enableHighAccuracy: false,
            timeout: 500,
            maximumAge: 5000
        };
        var markers = [];
        var myHub = jQuery.connection.getRoutes;

        if (navigator.geolocation) {

            navigator.geolocation.getCurrentPosition(currentPosition);
            navigator.geolocation.watchPosition(locUpdates, error_callback, options)
        }
        jQuery('#displayname').val(prompt('Enter your name:', ''));

        myHub.client.GetCoord = function (a, user) {

            for (var i = 0; i < markers.length; i++) {
                if(user == markers[i].id)
                {
                    var oldMark = markers[i].markerObject;
                    oldMark.setPosition(new google.maps.LatLng(a));
                    return;
                }
            }
            var mymarker2 = new google.maps.Marker({ position: a, map: map });
            mymarker2.setMap(map);
            markers.push({ id: user, markerObject: mymarker2 });
            var infowindow = new google.maps.InfoWindow({ content: "Hello " + user + " !" });
            infowindow.open(map, mymarker2);

            console.log("rec", a);
        };

        //jQuery.connection.hub.start().done(function () {

        //        myHub.server.send(jQuery('#displayname').val(), jQuery('#message').val());

        //});
        function currentPosition(pos) {
            currentLoc = new google.maps.LatLng(pos.coords.latitude, pos.coords.longitude);
            map = new google.maps.Map(document.getElementById('map'), {
                center: currentLoc,
                zoom: 16,
                mapTypeId: google.maps.MapTypeId.ROADMAP
            });

            mymarker = new google.maps.Marker({ position: currentLoc, map: map });
            mymarker.setMap(map);

            var infowindow = new google.maps.InfoWindow({ content: "Hello " + jQuery('#displayname').val() + " !" });
            infowindow.open(map, mymarker);
            markers.push({ id: jQuery('#displayname').val(), markerObject: mymarker });
            sendingCoord(currentLoc);
        }

        function sendingCoord(a) {
            console.log(jQuery.connection);
            jQuery.connection.hub.start().done(function () {

                myHub.server.sendCoord(a, jQuery('#displayname').val());
                console.log("send", a);
            });
        }

        function SaveCoordinates(a) {


        }
        

        //this.init_map = function(){
        //    var mapOptions = {
        //        center: new google.maps.LatLng(lat, lng),
        //        zoom: 17,
        //        mapTypeId: google.maps.MapTypeId.ROADMAP
        //    };
        //    map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
        //}

        //this.addMarker = function(lat, lng, id){
        //    var marker = new google.maps.Marker({
        //        position: new google.maps.LatLng(lat, lng),
        //        map: map,
        //        title:"I'm Here!"
        //    });
        //    markers.push({ id: id, markerObject: marker});
        //}

        //this.updateMarkerCoordinates(lat, lng, id){
        //    //I let you loop the markers array, compare ids and retrieve the marker
        //    marker.setPosition(new google.maps.LatLng(lat, lng));
        //}

        function locUpdates(pos) {
            currentLoc = new google.maps.LatLng(pos.coords.latitude, pos.coords.longitude);
            console.log(currentLoc);

            sendingCoord(currentLoc);
            //mymarker.setPosition(currentLoc);
            //map.setCenter(currentLoc);

        }
        function error_callback(error) {
            document.getElementById("errorcode").innerHTML = error.code;
            document.getElementById("errormsg").innerHTML = error.message;
        }
    });


</script>



    }







@*<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
<style>
    #mapid {
        height: 180px;
    }
</style>
<script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js">
</script>
<script type="text/javascript">
    
</script>

<h2>Map</h2>
<div>
    <div id="mapid"></div>
</div>*@

SignalRMapDemo/Views/Map/Leaflet.cshtml
@{
    //ViewBag.Title = "Leaflet";
}
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />
<style>#mapid { height: 500px; }</style>

<input type="hidden" id="displayname" />
<h2>Leaflet</h2>
<div class="col-lg-10" id="mapid"></div>
<div class="col-lg-2">
    <select class="form-control-static" id="ddlUsers">
    </select>
    <input type="button" id="btnSetCentre" value="View" />
</div>
<div id="errorcode"></div>
<div id="errormsg"></div>

@section scripts {

    <script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>

    <script src="~/Scripts/jquery.signalR-2.2.0.js"></script>
    <script src="~/signalr/hubs"></script>
    <script>


        jQuery(document).ready(function () {
            jQuery.ajaxSettings.traditional = true;

            var currentLoc; 
            var map;
            var mymarker;
            var options = {
                enableHighAccuracy: false,
                timeout: 500,
                maximumAge: 5000
            };
            var markers = [];
            var myHub = jQuery.connection.getRoutes;

            var polylineCoord;
            var polyline;

            if (navigator.geolocation) {

                navigator.geolocation.getCurrentPosition(currentPosition);
                navigator.geolocation.watchPosition(locUpdates, error_callback, options)
            }
            jQuery('#displayname').val(prompt('Enter your name:', ''));

            myHub.client.GetCoord = function (a, user) {
                var abc = '';
                for (var i = 0; i < markers.length; i++) {
                    abc += '<option value="' + markers[i].id + '">' + markers[i].id + '</option>';
                }
                jQuery('#ddlUsers').html(abc);

                for (var i = 0; i < markers.length; i++) {
                    if (user == markers[i].id) {
                        var oldMark = markers[i].markerObject;
                        oldMark.setLatLng(L.latLng(a));
                        return;
                    }
                }
                var mymarker2 = L.marker(L.latLng(a)).addTo(map);

                mymarker2.bindPopup("<b>Hello, Me " + user + " !</b><br>I am Here.").openPopup();

                markers.push({ id: user, markerObject: mymarker2 });

                //var abc = '';
                //for (var i = 0; i < markers.length; i++) {
                //    abc += '<option value="' + markers[i].markerObject.getLatLng() + '">' + markers[i].id + '</option>';
                //}
                //jQuery('#ddlUsers').html(abc);

                console.log("rec", a);
            };

            function currentPosition(pos) {

                currentLoc = L.latLng(pos.coords.latitude, pos.coords.longitude); //[pos.coords.latitude, pos.coords.longitude];

                map = L.map('mapid').setView(currentLoc, 16);

                console.log(map);

                L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
                    attribution: 'SHAHEEN',
                    maxZoom: 18,
                    id: 'faizu619.pdp6cle7',
                    accessToken: 'pk.eyJ1IjoiZmFpenU2MTkiLCJhIjoiY2lsdDViem5oMDA4Y3Vza3N0NWU4bHk3cCJ9.Fgy-HRATWonWZc2gAIoRbw'
                }).addTo(map);

                mymarker = L.marker(currentLoc).addTo(map);

                mymarker.bindPopup("<b>Hello, Me " + jQuery('#displayname').val() + " !</b><br>I am Here.").openPopup();

                markers.push({ id: jQuery('#displayname').val(), markerObject: mymarker });
                //saveCoord(currentLoc);

                sendingCoord(currentLoc);

                var ab = { userName: jQuery('#displayname').val(), latitude: pos.coords.latitude.toString(), longitude: pos.coords.longitude.toString() };
                saveCoord(ab);
                polyline = L.polyline(currentLoc, { color: 'red' }).addTo(map);
            }

            function sendingCoord(a) {
                //console.log(jQuery.connection);
                jQuery.connection.hub.start().done(function () {

                    myHub.server.sendCoord(a, jQuery('#displayname').val());
                    console.log("send", a);
                });
            }

            function saveCoord(a) {
                console.log("Savingg",a);
                var dataPost = JSON.stringify(a);
                 jQuery.ajax({
                    url: '/Map/Create',
                    type: 'POST',
                    data: "{ 'dataz' : '"+dataPost+"' }",
                    contentType: 'application/json; charset=utf-8',
                    success: function (data) {
                        alert(data);
                    },
                    error: function (e) {
                        alert(e.responseText);
                        console.log(e);
                    }
                });

            }

            function locUpdates(pos) {
                currentLoc = L.latLng(pos.coords.latitude, pos.coords.longitude);
                console.log(currentLoc);

                //saveCoord(currentLoc);
                var ab = { userName: jQuery('#displayname').val(), latitude: pos.coords.latitude.toString(), longitude: pos.coords.longitude.toString() };
                saveCoord(ab);

                sendingCoord(currentLoc);
                polyline.addLatLng(currentLoc);

            }
            function error_callback(error) {
                document.getElementById("errorcode").innerHTML = error.code;
                document.getElementById("errormsg").innerHTML = error.message;
            }

            jQuery('#btnSetCentre').click(function () {
                console.log(jQuery('#ddlUsers').val());
                for (var i = 0; i < markers.length; i++) {
                    if (jQuery('#ddlUsers').val() == markers[i].id) {
                        var oldMark = markers[i].markerObject.getLatLng();
                        console.log(jQuery('#ddlUsers').val(),oldMark);
                        map.setView(oldMark, 17);
                        return;
                    }
                }
                
            });

    });
   

    </script>



}

SignalRMapDemo/Views/Map/Mobile.cshtml
@{
    ViewBag.Title = "Mobile";
}

<style>
    body {
    padding: 0;
    margin: 0;
}
html, body, #map {
    height: 100%;
}

</style>

<h2>Mobile</h2>
<div id="map"></div>

@section scripts {
<script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>
    <script type="text/javascript">
        var map = L.map('map');

        L.tileLayer('https://api.tiles.mapbox.com/v4/MapID/997/256/{z}/{x}/{y}.png?access_token={accessToken}', {
            attribution: '',
            maxZoom: 18,
            id: 'faizu619.pdp6cle7',
            accessToken: 'pk.eyJ1IjoiZmFpenU2MTkiLCJhIjoiY2lsdDViem5oMDA4Y3Vza3N0NWU4bHk3cCJ9.Fgy-HRATWonWZc2gAIoRbw'
        }).addTo(map);

        map.locate({ setView: true, maxZoom: 16 });

        function onLocationFound(e) {
            var radius = e.accuracy / 2;

            L.marker(e.latlng).addTo(map)
                .bindPopup("You are within " + radius + " meters from this point").openPopup();

            L.circle(e.latlng, radius).addTo(map);
        }

        map.on('locationfound', onLocationFound);

        function onLocationError(e) {
            alert(e.message);
        }

        map.on('locationerror', onLocationError);

    </script>

}

SignalRMapDemo/Views/Map/NewMap.cshtml
@{
	ViewBag.Title = "Leaflet";
}
@*<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.css" />*@
<link href="~/Content/leaflet.css" rel="stylesheet" />
<style>
	#mapid {
		height: 500px;
	}
</style>


@if (ViewBag.userName == null)
{

	<form method="post">
		<input type="text" id="mytxt" name="userName" />
		<button type="submit">Submit</button>
	</form>
	@*using ( Html.BeginForm("NewMap", "Map", FormMethod.Post, new { @class = "my_form" }))
	{
	   <p>Your Name : @Html.TextBox("userName")</p>
	<input type="submit" name="Enter" value="Enter " />
	}*@
}

@if (ViewBag.userName != null)
{
	<input type="hidden" id="displayname" value="@ViewBag.userName" />
	<h2>Leaflet</h2>
	<div class="col-lg-10" id="mapid"></div>
	<div class="col-lg-2">
		<select class="form-control-static" id="ddlUsers"></select>
		<input type="button" id="btnSetCentre" value="View" />
	</div>
	<div id="errorcode"></div>
	<div id="errormsg"></div>
	<div id="accur"></div>

	@section scripts {

		@*<script src="http://cdn.leafletjs.com/leaflet/v0.7.7/leaflet.js"></script>*@

		<script src="~/Scripts/leaflet.js"></script>
		<script src="~/Scripts/jquery.signalR-2.2.0.js"></script>
		<script src="~/signalr/hubs"></script>
		<script src="~/Scripts/Leaflet.AccuratePosition.js"></script>
		<script>

			jQuery(document).ready(function () {

				//function loadjsfile(filename, callback) {

				//}
				var filename = '../Scripts/NewFile.js';

				var rnd = Math.floor(Math.random() * 80000);
				var fileref = document.createElement('script');
				fileref.setAttribute("type", "text/javascript");
				fileref.setAttribute("src", filename + "?r=" + rnd);

				var abc = jQuery('script');
				var done = false;
				fileref.onload = fileref.onreadystatechange = function () {
					if (!done && (!this.readyState
											|| this.readyState == "loaded"
											|| this.readyState == "complete")) {
						done = true;

						// Continue your code
						//callback();

						// Handle memory leak in IE
						fileref.onload = fileref.onreadystatechange = null;
						document.getElementsByTagName("script")[abc.length - 1].removeChild(fileref);
					}
				};
				//document.getElementsByTagName("script")[0].appendChild(fileref);


				console.log(abc);
				jQuery('script')[abc.length - 1].appendChild(fileref);
			});


		</script>
	}

}

SignalRMapDemo/Views/Map/PureLeaflet.cshtml
@{
	ViewBag.Title = "PureLeaflet";
}

<h2>@ViewBag.Title</h2>

<!-- Leaflet -->
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.css">
<script src="http://cdn.leafletjs.com/leaflet-0.7.3/leaflet.js"></script>
<!-- Accurate Position Plugin -->
<link rel="stylesheet" href="~/Content/style.css">
<script src="~/Scripts/Leaflet.AccuratePosition.js"></script>

<div id="map"></div>
<ul id="status" class="progressing">
	<li>Find accurate position … (Desired accuracy: 20)</li>
</ul>
<script>
	var map = L.map('map').setView([40.44695, -345.23437], 1);
	//var polyline = L.polyline([40.44695, -345.23437], { color: 'red' }).addTo(map);

	L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
		attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
	}).addTo(map);

	function onAccuratePositionError(e) {
		addStatus(e.message, 'error');
	}

	function onAccuratePositionProgress(e) {
		var message = 'Progressing … (Accuracy: ' + e.accuracy + ')';
		addStatus(message, 'progressing');
	}

	function onAccuratePositionFound(e) {
		var message = 'Most accurate position found (Accuracy: ' + e.accuracy + ')';
		addStatus(message, 'done');
		map.setView(e.latlng, 12);
		L.marker(e.latlng).addTo(map);
	    //polyline.addLatLng(e.latlng);
		console.log(e);
	}

	function addStatus(message, className) {
		var ul = document.getElementById('status'),
			li = document.createElement('li');
		li.appendChild(document.createTextNode(message));
		ul.className = className;
		ul.appendChild(li);
	}

	map.on('accuratepositionprogress', onAccuratePositionProgress);
	map.on('accuratepositionfound', onAccuratePositionFound);
	map.on('accuratepositionerror', onAccuratePositionError);

	map.findAccuratePosition({
		maxWait: 10000,
		desiredAccuracy: 20
	});
</script>

SignalRMapDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>